### ISSUE TITLE
Quests File Randomly, Unexpectedly Deletes

### ISSUE THREAD

**Issue by zerafox** [raGan262/Quester#38]
I am using Dev Build 5 from Jenkins, on a 1.7.9 Craft Bukkit server.

I finish creating quests, check through a Yaml Parser, and upload the file to my server. I issue a command /quest reload and then a /quest save to make sure the quests stay on server.
I then apply the quests their quest holders (NPCs) and recheck to make sure quests are still loaded onto server with /quest list. I reissue /quest save and for finality /save-all.

Quests will stick around in the quest.yml for a day or two through several restarts, but after a while the entire file will wind up completely empty and I will have to repeat the process.

I know there is nothing wrong with the Quest Parsing, I know I am saving the re-upload of my quests like crazy.
I do not know why the file (untouched after-wards) is deleting itself and rending my server without quests until I repeat the process all over again.

I haven't the faintest idea what causes this, nor do I have any seen error reports to give. I also cannot give any solid information on when this might be happening as it seems completely random with each server restart.
I do know that this is getting quite frustrating and making me weary about creating new Quests, or continuing to use this plugin. Which sucks, considering this is the best option for my needs available.

**Comment by ozm8** [comment]
I've had this problem before it usually happens when you edit a quest from the file not ig

**Comment by raGan262** [comment]
In that case it's very likely caused by invalid quest format. Turn the debug mode on and check console. You can also provide quests.yml with which this happens. I can't help you unless you give me some real evidence or steps to reproduce this behaviour.
