### ISSUE TITLE
Quester Plugin - Quester Not Working!

### ISSUE THREAD

**Issue by Knight927** [raGan262/Quester#48]
Hi i am a owner of a new minecraft server with the plugin Quester. The server is so you can do quests then complete them and get money to rank up to the next rank. But when ever someone tries to do the quest it says " You do not have permission to do this" It says that when ever they click on the quest holder. (Npc) . Please help! If you wanna come try my server ip is SynergyRealms.mymc.io Please Help !

**Comment by ozm8** [comment]
Hello I think I know a solution to this I had the same problem. I think it has to do with world guard type /region flag [Region name] use allow
