### ISSUE TITLE
Save/Load Problem

### ISSUE THREAD

**Issue by olafWal** [raGan262/Quester#51]
There is a problem in saving/loading quests.yml

I have 3 Quest, 2 of them work fine, but there is a Problem with saving/loading the 3rd.

Trying to describe the Problem (a bit difficult):

I have a working quests.yml, if I copy it to the plugin dir and do /q reload everything works fine.

After server restart, starting the quest with /q start <questname> does not start the quest but outputs a red "6".

After doing a /q reload everything works again.

**Comment by raGan262** [comment]
Please provide your quests.yml and console output after reloading and restarting.

**Comment by olafWal** [comment]
Get it at 
http://www.walkowiak.org/misc/mc/

mc.tar.gz contains the full install including all jar etc...

**Comment by raGan262** [comment]
The exception is thrown when quester tries to resolve nonexistent prerequisity of this objective:
```
'3':
  index: 15
  type: NPC
  prerequisites: '6'
```
Removing it or changing it to a valid objective id will fix your issue.

I will try improve error output in cases where it's lacking. Thanks for the report.
