### ISSUE TITLE
Unable to add WorldGuard command event

### ISSUE THREAD

**Issue by AshvaleStaff** [raGan262/Quester#52]
I would like to add the event 
/q event add 1 cmd region addmember innskeleton -w world %p

But Quester appears to be hijacking the '-w' in the command, so the console is saying that WorldGuard still needs a world name:

23.01 03:00:47 [Server] INFO Please specify the world with -w world_name.

I'm using Quester 0.7-4-SNAPSHOT on Spigot 1.7.10.

**Comment by raGan262** [comment]
Quote the command like this:
/q event add 1 cmd "region addmember innskeleton -w world %p"

**Comment by AshvaleStaff** [comment]
Works perfectly, thank you.
