### ISSUE TITLE
All Objectives Completed, Mission Not Finishing

### ISSUE THREAD

**Issue by AshvaleStaff** [raGan262/Quester#53]
It only seems to be occurring with this quest, once all objectives are completed and all events trigger the quest seems to freeze up. Typing /q progress will show;

Arachnophobia progress
- Completed
- Completed
- Completed
- Completed
- Completed
- Completed
- Completed

Here's the section of the quests.yml relating to this mission;
http://pastebucket.com/76784

I'm using Quester version 0.7-4-SNAPSHOT and Spigot 1.7.10 w/ 1.8 compatibility.

There are no errors being reported in Console. The player nor the console never receive any 'Quest Completed' prompts.

**Comment by raGan262** [comment]
Objective 1 has itself as a prerequisity. Therefore it is never activated and completed. 8 objectives - 7 Completed.
