### ISSUE TITLE
Quester Exception Error in 1.8 Spigot

### ISSUE THREAD

**Issue by zerafox** [raGan262/Quester#54]
Quester is continually spitting errors into console while the server is running.

04.02 21:10:42 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_45]
04.02 21:10:42 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.1943.jar:git-Spigot-d0d1d87-15e81cf]
04.02 21:10:42 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8.1943.jar:git-Spigot-d0d1d87-15e81cf]
04.02 21:10:42 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.1943.jar:git-Spigot-d0d1d87-15e81cf]
04.02 21:10:42 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot-1.8.1943.jar:git-Spigot-d0d1d87-15e81cf]
04.02 21:10:42 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.1943.jar:git-Spigot-d0d1d87-15e81cf]
04.02 21:10:42 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.1943.jar:git-Spigot-d0d1d87-15e81cf]
04.02 21:10:42 [Server] INFO at me.ragan262.quester.listeners.PositionListener.run(PositionListener.java:36) ~[?:?]
04.02 21:10:42 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
04.02 21:10:42 [Server] WARN Task #119 for Quester v0.7-4-SNAPSHOT generated an exception

Spigot 1.8 Build: 1943
Quester Dev Build: 13 / 0.7.5-Snapshot

**Comment by raGan262** [comment]
I'm pretty sure you are not using build 13 (v0.7.5-SNAPSHOT). Try redownloading it and see if it still happens.
