### ISSUE TITLE
NPCKILL objective doesn't work

### ISSUE THREAD

**Issue by Turaels** [raGan262/Quester#56]
When I use the objective " NPCKILL " with spigot 1.8.3, the objective work, but when I kill an npc the objectives does not count!

use build # 13
spigot 1.8.3

Sorry for my bad english im french

**Comment by brooklynstarr** [comment]
I can actually confirm this as an intermittent issue- it appears to work initially then stops. This is not limited to Quester though, I have the same problem with the Quests plugin as well- and there it does not recognize an NPC kill at all, so this may be an overall minecraft build issue. In the meantime, I've had to modify the objectives to work around it, which really kind of sucks.

**Comment by Turaels** [comment]
made in it is not a bug you have to download Citizensnpc here : http://ci.ragan262.me/job/QuesterNpcs/

**Comment by brooklynstarr** [comment]
Thanks for the update- glad it's working for you. I'll keep an eye on it; I'm already using questernpcs.
