### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by JesusChrysler** [raGan262/Quester#57]
I've recently downloaded the quester plugin (Version: 0.6.3.6) and I have set up some quests. When my players try and start a quest they receive "You don't have permission for this". I've added the permission node "quester.use.*" to the player group but still have no luck. Is there something I've done wrong?

**Comment by raGan262** [comment]
No, Quester 0.6 is not working too well with GroupManager, and it's likely that you just need to write each individual permission for it to work. If the problem persists, and you are reluctant to use up-to-date quester version from [here](http://ci.ragan262.me/job/Quester/), let me know. 0.7 dev builds are official builds for 1.7/1.8.

**Comment by JesusChrysler** [comment]
I'm assuming the individual permission are "quester.use.(Command)" e.g. quester.use.start. If they are they aren't working. I'm still getting the same response as before.

**Comment by raGan262** [comment]
Try using newest version then. (0.7) If all else fails, try different permission plugin.

**Comment by JesusChrysler** [comment]
Where could I find version 0.7, it does not show up in the files list on bukkit.
