### ISSUE TITLE
Objectives are deleted on restart!

### ISSUE THREAD

**Issue by Guarmanda** [raGan262/Quester#60]
When I create a quest, I also test it. I created 20 quests, then test them, the worked all. But on server restart, all objectives (only objectives) were deleted, in all quests. All my objectives are location objectives (/q location add loc here 3) and now, I must do all my quests 1 more time, so I really need help to fix this error! Log errors:
 [Quester] Error occured when deserializing objective ID 0 in quest 'Vers les cieux'.
 [Quester] Error occured when deserializing objective ID 1 in quest 'Vers les cieux'.
 [Quester] Error occured when deserializing objective ID 0 in quest 'ElÃ¨ve studieux!'.
 [Quester] Error occured when deserializing objective ID 0 in quest 'Des papiers, encore des papiers!'.
 [Quester] Error occured when deserializing objective ID 0 in quest 'Quel heure est-il ?'.
 [Quester] Error occured when deserializing objective ID 0 in quest 'Sauteur nÃ©'.
version: 0.6.3.6

**Comment by raGan262** [comment]
Please use version 0.7 from [here](https://copy.com/cnAAHbBH64uyi9Yi). If it happens with the new version as well, I will try to help. 
If you want to be sure about quests being saved, you can also use '/q save'.

**Comment by Guarmanda** [comment]
It works thanks
